### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by DevQA2001** [HammadRashid1997/50Projects50Days-Testing#38]
The Github readme needs to be updated. It needs to be more eye catching and attractive.

**Comment by HammadRashid1997** [comment]
Sure we can work on this. Any suggestions from your end would be appreciated!

**Comment by DevQA2001** [comment]
Yes, we can try to make it more appealing!
Like using icons or emojis etc

**Comment by HammadRashid1997** [comment]
Sure, I'll start working on it

**Comment by HammadRashid1997** [comment]
Done!
